#include<stdio.h>
#include<math.h>
int main(){
    int t;scanf("%d",&t);
    while(t--){
        int n;scanf("%d",&n);
        int d=0;
        while(n!=0){
           if(n>=1000){
            while(n>=1000){
                d++;
                n-=1000;
            }
           }
           if(n>=500){
            while(n>500){
                d++;
                n-=500;
            }
           }
           if(n>=200){
            while(n>=200){
                d++;
                n-=200;
            }
           }
           if(n>=100){
            while(n>=100){
                d++;
                n-=100;
            }
           }
           if(n>=50){
            while(n>=50){
                d++;
                n-=50;
            }
           }
           if(n>=20){
            while(n>=20){
                d++;
                n-=20;
            }
           }
           if(n>=10){
            while(n>=10){
                d++;
                n-=10;
            }
           }
           if(n>=5){
            while(n>=5){
                d++;
                n-=5;
            }
           }
           if(n>=2){
            while(n>=2){
                d++;
                n-=2;
            }
           }
           if(n>=1){
            while(n>=1){
                d++;
                n-=1;
            }
           }
        }
        printf("%d\n",d);
    }
}